export const MauCauTu = [
    ["tam giác [A-Z][A-Z][A-Z] = tam giác [A-Z][A-Z][A-Z]","tam giác 0 = tam giác 1"],
    ["[A-Z][A-z] [Tt]ia [A-Z][A-z] đối","Tia(0) đối Tia(1)"],
    ["[A-Z] nằm giữa hai điểm [A-Z] [A-Z]","0 nằm giữa 1, 2"],
    ["[A-Z] [A-Z] [A-Z] lần lượt là trung điểm của [A-Z][A-Z] [A-Z][A-Z] [A-Z][A-Z]","0 là trung điểm của 3;1 là trung điểm của 4;2 là trung điểm của 5"],
    ["[A-Z] [A-Z] lần lượt là trung điểm của [A-Z][A-Z] [A-Z][A-Z]","0 là trung điểm của 2;1 là trung điểm của 3"],
    ["[Tt]ia [A-Z][A-z] đối [Tt]ia [A-Z][A-z]","Tia(0) đối Tia(1)"],
    ["[A-Z] nằm giữa [A-Z] [A-Z]","0 nằm giữa 1,2"],
    ["[Tt]ia [A-Z][A-z] là tia phân giác của [Gg]óc [A-Z][A-Z][A-Z]","Tia (0) là phân giác của Góc(1)"],
    ["[A-Z][A-Z] là đường cao của tam giác vuông [A-Z][A-Z][A-Z]","0 là đường cao của tam giác vuông 1"],
    ["[A-Z][A-Z] là đường cao của tam giác [A-Z][A-Z][A-Z]","0 là đường cao của tam giác 1"],
    ["[A-Z][A-Z] là đường cao của hình thang [A-Z][A-Z][A-Z][A-Z]","0 là đường cao của hình thang 1"],
    ["[A-Z][A-Z] là đường cao của hình b[ìi]nh h[aà]nh [A-Z][A-Z][A-Z][A-Z]","0 là đường cao của hình bình hành 1"],
    ["[Tt]ia [A-z][A-z] nằm giữa [Tt]ia [A-Z][A-z] [Tt]ia [A-Z][A-z]","0 nằm giữa Tia(1), Tia(2)"],
    ["[A-Z][A-Z] là tia phân giác của góc [A-Z][A-Z][A-Z]","0 là phân giác của Góc(1)"],
    ["[A-Z][A-Z] là phân giác của góc [A-Z][A-Z][A-Z]","0 là phân giác của Góc(1)"],
    ["[A-Z] là giao điểm của [Tt]ia [A-Z][A-z] [A-Z][A-Z]","0 là giao điểm của Tia(1) và đoạn(2)"],
    ["[A-Z][A-Z] [A-Z][A-Z] cắt nhau tại [A-Z]","2 là giao điểm của 0, 1"],
    ["đường tròn tâm O R","đường tròn tâm O bán kính R"],
    ["[A-Z][A-Z] là tiếp tuyến của đường tròn tâm O bán [Kk]ính R","1 là tiếp tuyến của đường tròn tâm O bán kính R"],
    ["(3 điểm|) [A-Z] [A-Z] [A-Z] thẳng hàng", "0 1 2 Thẳng hàng"],
    ["3 điểm [A-Z] [A-Z] [A-Z] không thẳng hàng","0 1 2 không thẳng hàng"],
    ["[A-Z] nằm giữa [A-Z][A-Z]","0 nằm giữa 1"],
    ["[A-Z] không nằm giữa [A-Z][A-Z]", "0 không nằm giữa 1"],
    ["[A-Z] thuộc [A-Z][A-Z]","0 thuộc 1"],
    ["[A-Z] là trung điểm của [A-Z][A-Z]","0 là trung điểm của 1"],
    ["[A-Z] nằm giữa điểm [A-Z] [A-Z]","0 nằm giữa 1, 2"],
    ["[A-Z] thuộc đường tròn tâm [A-Z] bán kính [A-Z]", "0 thuộc đường tròn tâm 1 bán kính 2"],
    ["[A-Z][A-Z] là tiếp tuyến của đường tròn tâm [A-Z] bán kính [A-Z]","0 là tiếp tuyến của đường tròn tâm 1 bán kính 2"],
    ["đường tròn [A-Z] [A-Z]", "đường tròn tâm 0 bán kính 1"],
    ["[A-Z] là trung điểm của dây cung [A-Z][A-Z]","0 là trung điểm 1"],
    ["[A-Z] là giao điểm của [A-Z][A-Z] [A-Z][A-Z]","0 là giao điểm của 1 và 2"],
    ["[A-Z] thuộc Tia [A-Z][A-z]", "0 thuộc Tia(1)"]
];

//