export const MauCauHinh = [
    ["[Tt]am giác vuông cân [A-Z][A-Z][A-Z]","Tam giác vuông cân 0"],
    ["[Tt]am giác vuông [A-Z][A-Z][A-Z]","Tam giác vuông 0"],
    ["[Tt]am giác cân [A-Z][A-Z][A-Z]","Tam giác cân 0"],
    ["[Tt]am giác đều [A-Z][A-Z][A-Z]","Tam giác đều 0"],
    ["[Tt]am giác [A-Z][A-Z][A-Z]","Tam giác 0"],
    ["[Tt]ứ giác [A-Z][A-Z][A-Z][A-Z]","Tứ giác 0"],
    ["[Hh]ình chữ nhật [A-Z][A-Z][A-Z][A-Z]","Hình chữ nhật 0"],
    ["[Hh]ình vuông [A-Z][A-Z][A-Z][A-Z]","Hình vuông 0"],
    ["[Hh]ình thang [A-Z][A-Z][A-Z][A-Z]","Hình thang 0"],
    ["[Hh]ình bình hành [A-Z][A-Z][A-Z][A-Z]","Hình bình hành 0"],
    ["[Hh]ình thoi [A-Z][A-Z][A-Z][A-Z]","Hình thoi 0"],
    ["[Đđ]ường thẳng: [a-z]"],
    ["đường tròn tâm [A-Z] bán kính \\d*"],
];